version: '3'
services:
  mariadb:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=demogame
      - MYSQL_USER=ilkkamtk
      - MYSQL_PASSWORD=q1w2e3r4
      - MYSQL_ROOT_PASSWORD=q1w2e3r4
